### ISSUE TITLE
possible token corruption

### ISSUE THREAD

**Issue by ahmetb** [MarshallWace/cachenator#24]
https://github.com/MarshallWace/cachenator/blob/2aee48d94c7b238c6c8e0adec4a8247b814075b6/jwt.go#L54
this line is problematic as the token itself might also contain the sequence `Bearer`.

**Comment by uberspot** [comment]
Hi @ahmetb thanks for raising! 
Should be fixed in 0.17.3 I hope. 
Closing for now, if it re-appears feel free to re-open.
